### ISSUE TITLE
Let's have a logo!

### ISSUE THREAD

**Issue by rjz** [scalabridge/website#1]
....I'll go first!

![scala-bridge](https://cloud.githubusercontent.com/assets/499260/16402964/921640c0-3ca5-11e6-8aff-6e0b13a7fb40.png)

A quick note (HT @robinske) on fair use: the Scala Logo [is copyrighted](https://en.wikipedia.org/wiki/File:Scala_logo.png). Its incorporation in derivative works may constitute fair use, but we should obtain the EPFL's clarification and/or consent before adopting it in ScalaBridge material.

**Comment by robinske** [comment]
Thanks @rjz! Can you post the other options you shared with me? I'll follow up with someone at EPFL or the Scala Center about fair use!

**Comment by rjz** [comment]
Grayscale variation on the theme—

![scala-bridge-logo-2](https://cloud.githubusercontent.com/assets/499260/16536342/196457ea-3fa5-11e6-9cdc-860ab95b9bbb.png)

**Comment by rjz** [comment]
...and one that's a bit livelier.
 
![scala-bridge-logo-3](https://cloud.githubusercontent.com/assets/499260/16536358/3e43e59e-3fa5-11e6-87cc-1ebf98aa8205.png)

**Comment by robinske** [comment]
Talked to Heather Miller and got permission to use the Scala logo! I'm a fan of the first (and grayscale version), let's see if we can drum up some more ideas.
